Switched project name from directory name to package.json name attribute
stefanjudis/credits-cli pull request #99
Opened 2016-10-17 03:03 UTC by lannonbr

2016-10-17 04:39 UTC, Hypercubed commented
can you please do the following:

1) Add a fall back to use the directory name if package.json is not found or missing a name.
2) Add a /test/fixtures/package.json file.

Either one of these would pass the tests... but we should do both.

2016-10-17 12:18 UTC, Hypercubed commented
LGTM. cc/  @stefanjudis

2016-10-17 12:30 UTC, stefanjudis commented
Why not use simple `require` for reading the `package.json`?

Also not exactly sure, but does this line

```
projectName = JSON.parse( fs.readFileSync( creditPath + '/package.json' ) ).name;
```

work properly on windows? Having `/` 's in paths usually causes troubles. :)

But yeah overall looks good. :)

👍 

@Hypercubed @lannonbr

2016-10-17 12:53 UTC, Hypercubed commented
@stefanjudis Seams to work fine on windows... but to be safe I made a few comments.

@lannonbr If you can please address the above comments.  Also in cli.spec.js please add the line:

```
t.deepEqual( result[ 0 ] ), 'Credits for credits-cli-test' )
```

To match the change in the package.json.

2016-10-17 12:54 UTC, Hypercubed requested changes

2016-10-17 12:54 UTC, Hypercubed commented on cli.js
> +    projectName = JSON.parse( fs.readFileSync( creditPath + '/package.json' ) ).name;
replace with:

```
projectName = require( path.join( creditPath, '/package.json' ) ).name;
```

2016-10-17 12:54 UTC, Hypercubed commented on test/fixtures/package.json
> +    "name": "fixtures",
Please change to "name": "credits-cli-test",

2016-10-17 12:55 UTC, Hypercubed requested changes

2016-10-17 12:55 UTC, Hypercubed commented on cli.js
> +    projectName = JSON.parse( fs.readFileSync( creditPath + '/package.json' ) ).name;
projectName = require( path.join( creditPath, '/package.json' ) ).name;

2016-10-17 12:55 UTC, stefanjudis commented on cli.js
> +    projectName = JSON.parse( fs.readFileSync( creditPath + '/package.json' ) ).name;
Could we just use `require` here?

2016-10-17 15:19 UTC, stefanjudis commented
LGTM. 🚢

2016-10-18 07:53 UTC, Hypercubed approved these changes

2016-10-18 07:54 UTC, merged